/* Controlled benchmark, not a hardware FPS promise.
   WVR_THREE_PATH=... node tests/performance.cjs [baseline HTML path] */
const {chromium}=require('playwright'),fs=require('fs'),http=require('http'),path=require('path'),{execFileSync}=require('child_process');
(async()=>{const root=path.resolve(__dirname,'..');const baseline=process.argv[2]?fs.readFileSync(process.argv[2],'utf8'):execFileSync('git',['show','202e03f635312655f4b60365ae006c55c28f1ac2:index.html'],{cwd:root,encoding:'utf8',maxBuffer:1e7});
const server=http.createServer((q,r)=>{const html=q.url==='/before'?baseline:fs.readFileSync(root+'/index.html','utf8');r.setHeader('Content-Type','text/html');r.end(html.replace('window.__wvr = {','window.__wvr = { camera, renderer, spawnUnit, pushSnap, beginMatch, stopSim, puff, fx, get protocol(){return NET_VER;},'));});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||(fs.existsSync('/usr/bin/chromium')?'/usr/bin/chromium':undefined),headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader']});try{const results=[];
for(const version of ['before','after']){const page=await browser.newPage({viewport:{width:960,height:640}});await page.route('**/*',route=>{const u=route.request().url();if(u.includes('three.min.js')&&process.env.WVR_THREE_PATH)return route.fulfill({path:process.env.WVR_THREE_PATH,contentType:'application/javascript'});if(u.startsWith(url)||(!process.env.WVR_THREE_PATH&&u.includes('three.min.js')))return route.continue();return route.abort();});await page.goto(url+'/'+version);await page.waitForFunction(()=>window.__wvr);const errors=[];page.on('pageerror',e=>errors.push(e.message));
const metrics=await page.evaluate(()=>{const w=window.__wvr;const samples=[];let g,pathSearches=0;
for(let run=0;run<6;run++){g=w.newGame(['viking','rentner'],4242);g.cd=0;g.bears=[];g.itemT=1e9;g.towerOff=[true,true];for(let team=0;team<2;team++)for(let i=0;i<50;i++){w.spawnUnit(g,team,team?2:0);const u=g.units.at(-1),p=w.nw(-35+i%10*7,(team?-1:1)*(35+Math.floor(i/10)*6));Object.assign(u,{x:p.x,z:p.z,ord:{x:p.x,z:p.z,mv:false}});}const t=performance.now();for(let i=0;i<300;i++){w.step(g);pathSearches+=8-g.astarBudget;}if(run)samples.push(performance.now()-t);}
w.beginMatch('ai',['viking','rentner'],0,4242);w.V.delay=0;w.pushSnap(w.snapOf(g));return{simulationMs:samples.slice().sort((a,b)=>a-b)[2],simulationSamples:samples,pathSearches,units:g.units.length,snapshotBytes:JSON.stringify(w.snapOf(g)).length,heap:performance.memory?.usedJSHeapSize};});
await page.waitForTimeout(500);const draw=await page.evaluate(()=>{const w=window.__wvr;w.renderer.setPixelRatio(1);const sun=w.scene.children.find(o=>o.isDirectionalLight);sun.castShadow=false;w.renderer.shadowMap.enabled=false;w.renderer.info.autoReset=false;w.renderer.info.reset();w.renderer.render(w.scene,w.camera);const before=w.renderer.info.render.calls;const count=w.fx.puffs.length;for(const p of w.fx.puffs)if(p.m?.isMesh)p.m.visible=false;if(w.puffMesh)w.puffMesh.visible=false;w.renderer.info.reset();w.renderer.render(w.scene,w.camera);const withoutParticles=w.renderer.info.render.calls;return{drawCalls:before,withoutParticles,geometries:w.renderer.info.memory.geometries,textures:w.renderer.info.memory.textures};});
await page.evaluate(()=>{const w=window.__wvr;w.puff(0,2,0,0xffffff,160);});await page.waitForTimeout(50);const particles=await page.evaluate(()=>{const w=window.__wvr;for(const p of w.fx.puffs)if(p.m?.isMesh)p.m.visible=true;if(w.puffMesh)w.puffMesh.visible=true;w.renderer.info.reset();w.renderer.render(w.scene,w.camera);return{count:w.fx.puffs.length,calls:w.renderer.info.render.calls};});results.push({version,...metrics,...draw,particleBurst:particles,errors});await page.close();}
console.log(JSON.stringify(results,null,2));}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
